ltab=("\t\t\t\t\t\t\t\t\t\t\t")
ltab2=("\t\t\t\t\t\t\t\t\t")
ltab3=("\t\t")
ltab4=("\t\t\t\t")
ltab5=("\t\t\t")
billnum=int(input("enter bill no.:"))
date=input("ENTER DATE:")
name=input("ENTER PATIENT NAME : ")
sex=input("enter the sex of patient: ")
age=int(input("enter the age of patient: "))
mobno=int(input("ENTER Patient MOBILE NO : "))
docname=input("enter the doctor name:: ")
paymode=input("Enter payment type :")
pd=input("Enter product name 1 :- ")
pd1=input("Enter product name 2 :- ")
pd2=input("Enter product name 3 :- ")
qty=int(input("enter the qty. of product 1 :- "))
qty1=int(input("enter the qty. of product 2 :- "))
qty2=int(input("enter the qty. of product 3 :- "))
unitprice=int(input("enter the amt. of product 1:- "))
unitprice1=int(input("enter the amt. of product 2:- "))
unitprice2=int(input("enter the amt. of product 3:- "))
discount=int(input("enter the discount % :- "))
carrybag=input("enter yes or no for carry bag :- ")
amt=qty*unitprice
amt1=qty1*unitprice1
amt2=qty2*unitprice2
subtotal=amt+amt1+amt2
cgst=subtotal*0.06
sgst=subtotal*0.06
adiscount=subtotal-(subtotal*(discount/100))
print("*****************************************\n")
print("BILL NO:",billnum,ltab,"Invoice")
print("BEST Pharmacy",ltab2,"DATE:",date)
print("SITAPURA , JAIPUR")
print("www.bestpharmacy.com")
print("****************************************\n")
print("Patient : ",name)
print("SEX: ", sex)
print("MOBILE NUMBER:-",mobno)
print("AGE:- ",age)
print("DOC. NAME: ",docname)
print("PAYMENT TYPE : ",paymode)
print("****************************************\n")
print("Sr.No.",ltab3,"Product Name & Description",ltab3,"QTY.",ltab3,"UNIT PRICE",ltab3,"Amount(Rupees)")
print("1.    ",ltab3,pd ,ltab4,qty     ,ltab3,unitprice, ltab5,amt)
print("2.    ",ltab3,pd1,ltab4,qty1    ,ltab3,unitprice1,ltab5,amt1)
print("3.    ",ltab3,pd2,ltab4,qty2    ,ltab3,unitprice2,ltab5,amt2,"\n")
print(ltab,"Subtotal =",subtotal)
print(ltab,"CGST 6%  =", cgst )
print(ltab,"SGST 6%  =", sgst)
print(ltab,"Discount =",discount,"%")
print(ltab,"Amount after discount=",adiscount)
if carrybag=="YES" or "yes":
        carrybagprice=18
        totalamount=cgst+sgst+adiscount+carrybagprice
        print(ltab,"Carry Bag =",carrybag, "=",carrybagprice )
        print(ltab,"TotalAmount =",totalamount,"Rupees","\n")
        print("--------------------------------------------------------------------------------------------------------------------\n")
        print("Quality Medicine At Reasonable Price")
        print("All type of medicine are available")
        print("Thank YOU For Shopping")
else:
    carrybagprice=0
    totalamount=cgst+sgst+adiscount+carrybagprice
    print(ltab,"Carry Bag =",carrybag, "=",carrybagprice )
    print(ltab,"TotalAmount=",totalamount,"Rupees","\n")
    print("-------------------------------------------------------------------------------------------------------------------------\n")
    print("Quality Medicine At Reasonable Price")
    print("All type of medicine are available")
    print("Thank YOU For Shopping")